name: bash test
on: 
  workflow_dispatch:
    inputs:
      rid:
        description: workflow run id in Twitter_api repository
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          console.log(${{ inputs.rid }})

