name: bash test
on: 
  workflow_dispatch:
    inputs:
      rid:
        description: workflow run id in Twitter_api repository
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.rid }}
          curl -D- -XGET -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          "https://api.github.com/repos/popcube/Twitter_api/actions/runs/${{ inputs.rid }}/artifacts"

