name: bash test
on: 
  workflow_dispatch:
    inputs:
      rid:
        description: workflow run id in Twitter_api repository
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      
      - name: setup
        run: |
          sudo apt-get install jq          
          echo workflow run id is ${{ inputs.rid }}
        
      - name: get artifact id
        run: |        
          curl -XGET -s -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          "https://api.github.com/repos/popcube/Twitter_api/actions/runs/${{ inputs.rid }}/artifacts" |\
          jq -r '.artifacts[0].id | tostring | "artifact_id=" + .' | tee log.txt >> $GITHUB_ENV
          
          cat log.txt
          grep -e artifact_id=[0-9]+ log.txt ||\
          echo "artifact id is not found. fix bug or retry later" && exit 1
      
      - name: download artifact
        run: |
          echo "${{ env.artifact_id }}"
          
          curl -XGET -s -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          "https://api.github.com/repos/popcube/Twitter_api/actions/artifacts/${{ env.artifact_id }}/zip" \
          -L -o "twt_api.zip"
          
          ls -la
          
          unzip twt_api.zip
          ls -la
          cat goodday.txt
          

