name: bash test
on: [workflow_dispatch, push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -h "Authorization: Bearer ${{ secrets.TWT_BEARER_TOKEN }}" https://api.twitter.com/2/users/by/username/pj_sekai

