name: react build
on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
      
      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Getting Ready
        run: |
          git config user.name "react build bot"
          git config user.email ${{ secrets.MY_EMAIL }}
          git remote set-url origin https://popcube:${{ secrets.MY_TOKEN }}@github.com/popcube/prosekacube.git
          npm install
      
      - name: main run
        run: |
          mv ./docs ./src/docs
          ls -la src/docs/figs
          ls -la src/docs/figs/latest
          echo
          echo
          py scripts/make_mad_skillz_imgs_js.py
          echo
          echo
          npm run deploy
          
